apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-workload-generator-producer
  namespace: ros
spec:
  replicas: 0
  selector:
    matchLabels:
      app.kubernetes.io/component: producer
      app.kubernetes.io/instance: mq-workload-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: producer
        app.kubernetes.io/instance: mq-workload-generator
    spec:
      containers:
      - name: producer
        image: sspirits/mq-workload-generator:latest
        env:
          - name: MODE
            value: "producer"
          - name: PARALLELISM
            value: "1"
          - name: QPS
            value: "500"
          - name: ACCESS_POINT
            value: "automq-for-rocketmq-broker:8081"
          - name: TOPIC
            value: "long_running"
          - name: GROUP
            value: "automq_workload_generator"
          - name: ACCESS_KEY
            value: "dQy7poTQyS"
          - name: SECRET_KEY
            value: "LWghSS7fPWKRvOVvPHaG"
        imagePullPolicy: IfNotPresent
      restartPolicy: Always