apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-workload-generator-consumer
  namespace: benchmark
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: consumer
      app.kubernetes.io/instance: mq-workload-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: consumer
        app.kubernetes.io/instance: mq-workload-generator
    spec:
      containers:
      - name: consumer
        image: sspirits/mq-workload-generator:latest
        env:
          - name: DRIVER
            value: "kafka"
          - name: MODE
            value: "consumer"
          - name: PARALLELISM
            value: "1"
          - name: ACCESS_POINT
            value: "localhost:9092"
          - name: TOPIC
            value: "test"
          - name: GROUP
            value: "automq_workload_generator"
        imagePullPolicy: Always
      restartPolicy: Always