apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-workload-generator-producer
  namespace: benchmark
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: producer
      app.kubernetes.io/instance: mq-workload-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: producer
        app.kubernetes.io/instance: mq-workload-generator
    spec:
      containers:
      - name: producer
        image: sspirits/mq-workload-generator:0.2.0
        env:
          - name: DRIVER
            value: "kafka"
          - name: MODE
            value: "producer"
          - name: PARALLELISM
            value: "1"
          - name: QPS
            value: "10000"
          - name: ACCESS_POINT
            value: "localhost:9092"
          - name: TOPIC
            value: "test"
          - name: GROUP
            value: "automq_workload_generator"
        imagePullPolicy: Always
      restartPolicy: Always