apiVersion: apps/v1
kind: Deployment
metadata:
  name: mq-workload-generator-consumer
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/component: consumer
      app.kubernetes.io/instance: mq-workload-generator
  template:
    metadata:
      labels:
        app.kubernetes.io/component: consumer
        app.kubernetes.io/instance: mq-workload-generator
    spec:
      containers:
      - name: consumer
        image: sspirits/mq-workload-generator:latest
        env:
          - name: MODE
            value: "consumer"
          - name: PARALLELISM
            value: "4"
          - name: QPS
            value: "2500"
          - name: ACCESS_POINT
            value: "automq-for-rocketmq-broker:8081"
          - name: TOPIC
            value: "long_running"
          - name: GROUP
            value: "automq_workload_generator"
          - name: ACCESS_KEY
            value: "dQy7poTQyS"
          - name: SECRET_KEY
            value: "LWghSS7fPWKRvOVvPHaG"
        imagePullPolicy: Always
      restartPolicy: Always